In [3]:
import numpy as np

#Creating sample array
arr = np.arange(0,11)


In [4]:
#Get a value at an index
arr[8]




8

In [5]:
#Get values in a range
arr[1:5]


array([1, 2, 3, 4])

In [26]:


#Get values in a range
arr[0:5]


array([99, 99, 99, 99, 99])

In [27]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr


array([100, 100, 100, 100, 100,  99,   6,   7,   8,   9,  10])

In [28]:
# Reset array, we'll see why i had to reset in  a moment
arr = np.arange(0,11)



In [29]:

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#Important notes on Slices
slice_of_arr = arr[0:6]

In [31]:

#Show slice
slice_of_arr


array([0, 1, 2, 3, 4, 5])

In [32]:
#Change Slice
slice_of_arr[:]=99

In [33]:

#Show Slice again
slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [34]:
# Now note the changes also occur in our original array!
arr



array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy



array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [36]:
# Indexing a 2D array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [38]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]



20

In [39]:
# Getting individual element value
arr_2d[1,0]


20

In [40]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]



array([[10, 15],
       [25, 30]])

In [43]:
#Shape bottom row

arr_2d[2]

array([35, 40, 45])

In [44]:
#Shape bottom row
arr_2d[2,:]


array([35, 40, 45])

In [47]:


#Set up matrix
arr2d = np.zeros((10,10))

In [48]:
#Length of array
arr_length = arr2d.shape[1]

In [49]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [50]:
#Fancy indexing allows the following
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [51]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])