In [13]:

import numpy as np

#Takes care of floats


arr1 = np.array([[1,2,3],[8,9,10]])

arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [7]:
#Subtraction
arr1-arr1




array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [10]:
#Arithmetic operations with scalars on array
1 / arr1
print(arr1)

[[ 1  2  3]
 [ 8  9 10]]


In [15]:
#Exponential operation
arr1 * 3

array([[ 3,  6,  9],
       [24, 27, 30]])

In [18]:
arr = np.arange(0,11)
#Show
arr



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
#Get a value at an index
arr[8]

8