In [15]:

capitals = {'United States': 'Washington, DC','France': 'Paris','Italy': 'Rome'}



In [16]:
capitals

{'France': 'Paris', 'Italy': 'Rome', 'United States': 'Washington, DC'}

In [20]:
capitals['United States'] = 'Madrid'
capitals
bycapital = {capitals[key]: key for key in capitals.keys()}

In [18]:
morecapitals = {'Germany': 'Berlin','United States': 'London'}
capitals.update(morecapitals)
capitals



{'France': 'Paris',
 'Germany': 'Berlin',
 'Italy': 'Rome',
 'United States': 'London'}

In [19]:

squares = []

for i in range(10):
    squares.append(i**2)

squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [6]:
square={}
for i in range(3):
square[i]=i**2 


IndentationError: expected an indented block (<ipython-input-6-62af537388b3>, line 3)

In [7]:
print (square)

NameError: name 'square' is not defined

In [28]:
import numpy as np
my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)
#Print out array

my_array1


array([1, 2, 3, 4])

In [29]:
# Make another list
my_list2 = [11,22,33]
my_list =[my_list2,my_list1]


#Make multi-dimensional array
my_array2 = np.array(my_list)

#Show array
my_array2

array([[11, 22, 33], [1, 2, 3, 4]], dtype=object)

In [30]:
my_array2.shape 

(2,)

In [31]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
np.ones((1,5))


array([[ 1.,  1.,  1.,  1.,  1.]])

In [38]:
np.empty(5)
np.empty((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [40]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])